name: ml
channels:
- conda-forge
- defaults
dependencies:
- keras=2.0.9=py36_0
- tensorflow=1.0.0=py36_0
- xgboost=0.6a2=py36_0
- appnope=0.1.0=py36_0
- bkcharts=0.2=py36_0
- bleach=1.5.0=py36_0
- bokeh=0.12.7=py36_0
- cairo=1.14.8=0
- certifi=2016.2.28=py36_0
- click=6.7=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_0
- flask=0.12.2=py36_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gettext=0.19.8=1
- glib=2.50.2=1
- graphviz=2.38.0=4
- gsl=2.2.1=0
- h5py=2.7.0=np113py36_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- krb5=1.13.2=0
- libffi=3.2.1=1
- libgcc=4.8.5=1
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libprotobuf=3.2.0=0
- libssh2=1.8.0=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.8.0=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- mock=2.0.0=py36_0
- nbconvert=5.2.1=py36_0
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- nltk=3.2.4=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_0
- pandocfilters=1.4.2=py36_0
- pango=1.40.3=1
- path.py=10.3.1=py36_0
- patsy=0.4.1=py36_0
- pbr=1.10.0=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- plotly=2.0.11=py36_0
- prompt_toolkit=1.0.15=py36_0
- protobuf=3.2.0=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=2
- qtconsole=4.3.1=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- scipy=0.19.1=np113py36_0
- seaborn=0.8=py36_0
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np113py36_0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=0
- tornado=4.5.2=py36_0
- tqdm=4.15.0=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- xlrd=1.1.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.11=0
- pip:
  - chardet==3.0.4
  - colorlover==0.2.1
  - cufflinks==0.12.0
  - dash==0.19.0
  - dash-core-components==0.14.0
  - dash-html-components==0.8.0
  - dash-renderer==0.11.1
  - flask-compress==1.4.0
  - future==0.16.0
  - idna==2.6
  - imbalanced-learn==0.3.1
  - imblearn==0.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - mglearn==0.1.6
  - mlxtend==0.9.1
  - pandas-datareader==0.5.0
  - prompt-toolkit==1.0.15
  - pydot==1.2.3
  - pydot-ng==1.0.0
  - pyowm==2.7.1
  - requests-file==1.4.2
  - requests-ftp==0.3.1
  - scikit-learn==0.19.1
  - sodapy==1.4.5
  - urllib3==1.22
  - version-information==1.0.3
  - watermark==1.5.0
prefix: /Users/anujkatiyal/miniconda3/envs/ml

